### ISSUE TITLE
Segmentation Fault in Conda Binaries

### ISSUE THREAD

**Issue by Olllom** [beniz/libcmaes#189]
Hi,

I get a segmentation fault when linking against the linux libraries from conda-forge. [I use the introductory example from the github README as a part of my test suite.]

When compiling with my system gcc 4.8, the code runs fine.
When compiling with recent conda compilers (the packages gxx_impl_linux-64 and gxx_linux-64), e.g. version 7.2.0, the test fails.

The top of the stack trace is
```
Program received signal SIGSEGV, Segmentation fault.
0x00005555556a231f in <lambda(double const*, int)>::operator()(const double *, int) const (__closure=0x7fffffff8c40, x=0x402414f4a55ea55d, N=10) at /scratch/my_library/src/tests/Optimization_test.cpp:78
78          val += x[i]*x[i];
(gdb) bt
#0  0x00005555556a231f in <lambda(double const*, int)>::operator()(const double *, int) const (__closure=0x7fffffff8c40, x=0x402414f4a55ea55d, N=10) at /scratch/my_library/src/tests/Optimization_test.cpp:78
#1  0x00005555556a27ee in std::_Function_handler<double(double const*, int const&), <lambda(double const*, int)> >::_M_invoke(const std::_Any_data &, <unknown type in /scratch/my_library/build/tests/tests, CU 0x2bca28, DIE 0x37777b>, const int &) (__functor=..., __args#0=<unknown type in /scratch/my_library/build/tests/tests, CU 0x2bca28, DIE 0x37777b>, __args#1=@0x7fffffff8194: 10)
    at /my/home/.conda/envs/libcmaes2/x86_64-conda_cos6-linux-gnu/include/c++/7.2.0/bits/std_function.h:302
#2  0x00007ffff78bf05f in std::function<double (double const*, int const&)>::operator()(double const*, int const&) const (this=0x7fffffff8c40, __args#0=0x55555598b410, __args#1=@0x7fffffff8194: 10)
   from /my/home/.conda/envs/libcmaes2/lib/libmy_library.so
#3  0x00007ffff7925817 in libcmaes::ESOStrategy<libcmaes::CMAParameters<libcmaes::GenoPheno<libcmaes::NoBoundStrategy, libcmaes::NoScalingStrategy> >, libcmaes::CMASolutions, libcmaes::CMAStopCriteria<libcmaes::GenoPheno<libcmaes::NoBoundStrategy, libcmaes::NoScalingStrategy> > >::eval(Eigen::Matrix<double, -1, -1, 0, -1, -1> const&, Eigen::Matrix<double, -1, -1, 0, -1, -1> const&) [clone ._omp_fn.0] ()
   from /my/home/.conda/envs/libcmaes2/lib/libmy_library.so
#4  0x00007ffff7927dce in libcmaes::ESOStrategy<libcmaes::CMAParameters<libcmaes::GenoPheno<libcmaes::NoBoundStrategy, libcmaes::NoScalingStrategy> >, libcmaes::CMASolutions, libcmaes::CMAStopCriteria<libcmaes::GenoPheno<libcmaes::NoBoundStrategy, libcmaes::NoScalingStrategy> > >::eval (this=0x7fffffff8c40, candidates=..., phenocandidates=...) from /my/home/.conda/envs/libcmaes2/lib/libmy_library.so
```

Same for the shared libraries

```
Program received signal SIGSEGV, Segmentation fault.
0x00005555556a251f in <lambda(double const*, int)>::operator()(const double *, int) const (__closure=0x7fffffff8c40, x=0x4024296b31aa225b, N=10) at /scratch/my_library/src/tests/Optimization_test.cpp:78
78          val += x[i]*x[i];
(gdb) bt
#0  0x00005555556a251f in <lambda(double const*, int)>::operator()(const double *, int) const (__closure=0x7fffffff8c40, x=0x4024296b31aa225b, N=10) at /scratch/my_library/src/tests/Optimization_test.cpp:78
#1  0x00005555556a29ee in std::_Function_handler<double(double const*, int const&), <lambda(double const*, int)> >::_M_invoke(const std::_Any_data &, <unknown type in /scratch/my_library/build/tests/tests, CU 0x2bca28, DIE 0x37777b>, const int &) (__functor=..., __args#0=<unknown type in /scratch/my_library/build/tests/tests, CU 0x2bca28, DIE 0x37777b>, __args#1=@0x7fffffff8194: 10)
    at /my/home/.conda/envs/libcmaes2/x86_64-conda_cos6-linux-gnu/include/c++/7.2.0/bits/std_function.h:302
#2  0x00007ffff7129f03 in std::function<double (double const*, int const&)>::operator()(double const*, int const&) const (this=0x7fffffff8c40, __args#0=0x55555598b9d0, __args#1=@0x7fffffff8194: 10)
   from /my/home/.conda/envs/libcmaes2/lib/libcmaes.so.0
#3  0x00007ffff71ad27f in libcmaes::ESOStrategy<libcmaes::CMAParameters<libcmaes::GenoPheno<libcmaes::NoBoundStrategy, libcmaes::NoScalingStrategy> >, libcmaes::CMASolutions, libcmaes::CMAStopCriteria<libcmaes::GenoPheno<libcmaes::NoBoundStrategy, libcmaes::NoScalingStrategy> > >::eval(Eigen::Matrix<double, -1, -1, 0, -1, -1> const&, Eigen::Matrix<double, -1, -1, 0, -1, -1> const&) [clone ._omp_fn.0] ()
   from /my/home/.conda/envs/libcmaes2/lib/libcmaes.so.0
#4  0x00007ffff71af836 in libcmaes::ESOStrategy<libcmaes::CMAParameters<libcmaes::GenoPheno<libcmaes::NoBoundStrategy, libcmaes::NoScalingStrategy> >, libcmaes::CMASolutions, libcmaes::CMAStopCriteria<libcmaes::GenoPheno<libcmaes::NoBoundStrategy, libcmaes::NoScalingStrategy> > >::eval (this=0x7fffffff8c40, candidates=..., phenocandidates=...) from /my/home/.conda/envs/libcmaes2/lib/libcmaes.so.0

```

Any ideas?

**Comment by beniz** [comment]
Hi, I'm not familiar with conda compilers. Check the build flags and make sure they are the same as those used with straight GCC and that works. I've removed some special flags that were the cause of some issues when linking to external programs built with less optimization so make sure you are on the last version. 

Now, it's possible there are issues with GCC 7.2 that appears to be used here. You may want to check on that by building with GCC 7.2 outside conda as well. Best would be to report on the repository test samples so that it can be reproduced.

Thanks for the report and the stack trace btw, very useful!

**Comment by Olllom** [comment]
Hi, 
Thanks for your ideas. Could be that my compiler flags collide with those that were used to generate the binaries. 

There are NO general issues with gcc 7.2. When I compile libcmaes and my program with the above-mentioned gcc from conda, they play together well (using the cmake build workflow).

My temporary workaround is to compile libcmaes during the conda-build and distribute it with my conda package. This is kind of an ugly hack, but it should work for now.
